<?php 

define("EMAIL_PREFERENCE_NEW_FRIEND_REQUEST", 1);
define("EMAIL_PREFERENCE_NEW_MAIL_MESSAGE", 		EMAIL_PREFERENCE_NEW_FRIEND_REQUEST << 1);
define("EMAIL_PREFERENCE_INCOMING_OFFER", 			EMAIL_PREFERENCE_NEW_MAIL_MESSAGE << 1);
define("EMAIL_PREFERENCE_OFFER_ACCEPTED", 			EMAIL_PREFERENCE_INCOMING_OFFER << 1);
define("EMAIL_PREFERENCE_SHIP_DATES_UPDATED", 		EMAIL_PREFERENCE_OFFER_ACCEPTED << 1);
define("EMAIL_PREFERENCE_BOTTLES_RECEIVED", 		EMAIL_PREFERENCE_SHIP_DATES_UPDATED << 1);
define("EMAIL_PREFERENCE_BOTTLES_SHIPPED", 			EMAIL_PREFERENCE_BOTTLES_RECEIVED << 1);
define("EMAIL_PREFERENCE_TRADE_CLOSED", 			EMAIL_PREFERENCE_BOTTLES_SHIPPED << 1);
define("EMAIL_PREFERENCE_TRADER_REVIEWS", 			EMAIL_PREFERENCE_TRADE_CLOSED << 1);
define("EMAIL_PREFERENCE_TRADE_MESSAGE", 			EMAIL_PREFERENCE_TRADER_REVIEWS << 1);
define("EMAIL_PREFERENCE_OFFER_DECLINED", 			EMAIL_PREFERENCE_TRADE_MESSAGE << 1);
define("EMAIL_PREFERENCE_ALL", 0xFFFFFFFF);
define("EMAIL_PREFERENCE_NONE", 0);

class EmailPreference
{
	const NewFriendRequest = EMAIL_PREFERENCE_NEW_FRIEND_REQUEST;
	const NewMailMessage = EMAIL_PREFERENCE_NEW_MAIL_MESSAGE;
	const IncomingOffer = EMAIL_PREFERENCE_INCOMING_OFFER;
	const OfferAccepted = EMAIL_PREFERENCE_OFFER_ACCEPTED;
	const OfferDeclined = EMAIL_PREFERENCE_OFFER_DECLINED;
	const ShipDatesUpdated = EMAIL_PREFERENCE_SHIP_DATES_UPDATED;
	const BottlesReceived = EMAIL_PREFERENCE_BOTTLES_RECEIVED;
	const BottlesShipped = EMAIL_PREFERENCE_BOTTLES_SHIPPED;
	const TradeClosed = EMAIL_PREFERENCE_TRADE_CLOSED;
	const TraderReviews = EMAIL_PREFERENCE_TRADER_REVIEWS;
	const TradeMessage = EMAIL_PREFERENCE_TRADE_MESSAGE;
	const All = EMAIL_PREFERENCE_ALL;
	const None = EMAIL_PREFERENCE_NONE;
}

?>